// Internal SqlPart hierarchy.
//
// `Fragment` carries a tagged-template literal (strings + values) the user
// produced via the `sql` tag. The other classes are produced by the named
// helpers (`sql.id`, `sql.unsafe`, `sql.cast`, `sql.raw`) and signal "splice
// this into the SQL text rather than encode as a parameter."
//
// All five subclasses extend `SqlPart` so the materializer can detect them
// with a single `instanceof SqlPart` check on the fast path — that single
// check is the difference between "all values are plain parameters, just
// concat" and "we need to flatten / renumber / quote."

export abstract class SqlPart {}

/**
 * A tagged-template invocation.
 *
 * `strings.length === values.length + 1` — the standard tagged-template invariant.
 * For composition, fragments may appear inside another fragment's `values`; the
 * materializer flattens nested fragments and renumbers their parameter slots.
 */
export class Fragment extends SqlPart {
  constructor(
    readonly strings: readonly string[],
    readonly values: readonly unknown[],
  ) {
    super();
  }
}

/** Quoted SQL identifier (column / table / schema). Multi-part is dotted: `"schema"."table"`. */
export class Identifier extends SqlPart {
  constructor(readonly parts: readonly string[]) {
    super();
  }
}

/** Verbatim SQL text. Documented as the escape hatch — name shows up in code review. */
export class Unsafe extends SqlPart {
  constructor(readonly text: string) {
    super();
  }
}

/** A parameter with an explicit type cast (`$N::type`). Useful for null params. */
export class Cast extends SqlPart {
  constructor(
    readonly value: unknown,
    readonly type: string,
  ) {
    super();
  }
}

/**
 * Multi-row VALUES expansion for bulk insert. Generated by `sql.values(rows)`.
 *
 *   sql`insert into users ${sql.values(records, ['email', 'name'])}`
 *   → insert into users ("email", "name") values ($1, $2), ($3, $4), …
 *
 * The materialiser emits the column list once, then one parenthesised tuple
 * per row; each cell becomes a regular `$N` parameter, so codecs handle
 * encoding the same way they do for any other slot.
 */
export class ValuesList extends SqlPart {
  constructor(
    readonly rows: ReadonlyArray<Readonly<Record<string, unknown>>>,
    readonly columns: readonly string[],
  ) {
    super();
  }
}
